name: Doc powered RAG workflow

on:
  pull_request :
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: checking branch
        uses: actions/checkout@v2

  runnning-tests:
    runs-on: ubuntu-latest
    steps:
      - name : Running-python tests
        shell : bash
        run: |
          ./cli.sh
          
    


