name: Doc powered RAG workflow

on:
  push:
    branches: [ main ]
    paths:
      - 'doc-powered-rag/**'
      - '.github/workflows/doc-powered-rag*.yml'
jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: checking branch
        uses: actions/checkout@v2

      - name: List all files in the root directory
        run: |
          echo "Files in the root directory:"
            ls -al
        shell: bash

  runnning-tests:
    runs-on: ubuntu-latest
    steps:
      - name: List all files in the root directory
        run: |
          echo "Files in the root directory:"
            ls -al
        shell: bash
      - name : Running-python tests
        shell : bash
        run: |
          ls
          cd doc-powered-rag
          ./cli.sh
          
    


